// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CleanBinAndObj
{
    internal sealed partial class Vsix
    {
        public const string Id = "CleanBinAndObj.94f24be0-b7ee-4f99-9679-8a64ee82b079";
        public const string Name = "Clean Bin and Obj";
        public const string Description = @"Adds command to clean bin and obj directories in solution
";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "samanazadi1996";
        public const string Tags = "";
    }
}
